### ISSUE TITLE
lixee expose EASF01 (HC) and  EAS02(HP) as home assistant statistics

### ISSUE THREAD

**Issue by traylenator** [vk496/zigbee-herdsman-converters#12]
Been running Zlinky_TIC for a week now - all perfect - thankyou.

Currently only the total energy is exposed as a statistic and so is easy to add home assistant energy dashboard.

```
// For HomeAssistant                                                                                                                                                                            
const indexEnergy = () => exposes.numeric('energy', ea.STATE).withUnit('Wh').withDescription('Index Base').withProperty('currentSummDelivered');  
```

In my case the metrics EASF01 and EASF02 seem to correspond the Wh accumulated in off-peak (HC) and peak(HP) 

If these were both statistics  I could add these two statistics as independent energy inputs and improve the visualisation.

No clue how standard that mapping is, a quick google suggests it is not.

Thanks again.

Steve.

HA Statistic - https://www.home-assistant.io/more-info/statistics/

**Comment by traylenator** [comment]
In fact this can be achieved with a customization to add attributes to the
sensor of choice.

```yaml
homeassistant:
  customize:
    sensor.linky_easf01:
       friendly_name: "Total Off-Peak Rate Energy (HC)"
       state_class: total
       device_class: energy
    sensor.linky_easf02:
       friendly_name: "Total Peak Rate Energy (HP)"
       state_class: total
       device_class: energy
```
